# Generated by Django 6.0.4 on 2026-05-01 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_exam_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='is_published',
        ),
    ]
