# Generated by Django 6.0.4 on 2026-05-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_exam_results_active_exam_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='is_published',
        ),
        migrations.AddField(
            model_name='exam',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
