# Generated by Django 6.0.4 on 2026-05-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_exam_is_published_exam_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='is_active',
        ),
        migrations.AddField(
            model_name='exam',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
