# Generated by Django 6.0.4 on 2026-05-01 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_exam_is_active_exam_is_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='is_published',
            new_name='is_visible',
        ),
    ]
